import { z } from "zod";

export const financialDataSchema = z
    .object({
        monthlyIncome: z.number().min(0).max(100000000),
        expenses: z.record(z.number().min(0)),
        assets: z.record(z.number().min(0)),
        liabilities: z.record(z.number().min(0)),
        riskAppetite: z.enum(["low", "medium", "high"]),
    })
    .strict();

export const insightsRequestSchema = z
    .object({
        data: financialDataSchema,
        metrics: z.record(z.any()), // Metrics are generated by frontend, passed down
        dataHash: z.string().min(1),
    })
    .strict();
