import { z } from "zod";

export const financialDataSchema = z
    .object({
        monthlyIncome: z.number().min(0).max(100000000),
        expenses: z.record(z.number().min(0)),
        assets: z.record(z.number().min(0)),
        liabilities: z.record(z.number().min(0)),
        riskAppetite: z.enum(["low", "medium", "high"]),
        ageRange: z
            .enum([
                "under_20",
                "20_25",
                "26_30",
                "31_35",
                "36_40",
                "41_45",
                "46_50",
                "51_55",
                "56_60",
                "above_60",
            ])
            .optional(),
        targetRetirementCorpus: z.number().min(0).max(100000000000).optional(),
    })
    .strict();

export const insightsRequestSchema = z
    .object({
        data: financialDataSchema,
        metrics: z.record(z.any()), // Metrics are generated by frontend, passed down
        dataHash: z.string().min(1),
    })
    .strict();
